name: Run Tests

on:
    push:
        branches:
            - main

    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.0, 8.1, 8.2]
                laravel: [9.*]
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                    - laravel: 9.*
                      testbench: 7.*

        name: P${{ matrix.php }} / L${{ matrix.laravel }} / ${{ matrix.dependency-version }}

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_DATABASE: model_typer
                    MYSQL_HOST: 127.0.0.1
                    MYSQL_USER: test
                    MYSQL_PASSWORD: root
                    MYSQL_ROOT_PASSWORD: root
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/files
                  key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
                  coverage: none

            - name: 🔨 Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
            - name: Execute tests
              run: 🧪 vendor/bin/phpunit
